/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject.gui;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import miniproject.Details.AccountDetails;
import miniproject.Face.FaceCapture;
import miniproject.Utils.SendEmail;
import student_database.Student_database;

/**
 *
 * @author jaydutt
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public static boolean cinfirm_window=false;
    public static boolean csFrame=false;
    FaceCapture capture;
    String path="C:\\Users\\admin\\Documents\\NetBeansProjects\\miniProject";
            
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RootPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminButton = new javax.swing.JButton();
        LogINButton = new javax.swing.JButton();
        SignINButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        AttandanceButton1 = new javax.swing.JButton();
        DetailsPanel = new javax.swing.JPanel();
        Attandance = new javax.swing.JPanel();
        AddandancekeeperRootLabel = new javax.swing.JLabel();
        FaceIdRootLabel = new javax.swing.JLabel();
        FaceID = new javax.swing.JLabel();
        Note = new javax.swing.JLabel();
        AddFaceID = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        confirm = new javax.swing.JButton();
        LogIn = new javax.swing.JPanel();
        loginRootlabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        NameTextField_login = new javax.swing.JTextField();
        RollNoLabel = new javax.swing.JLabel();
        RollNoTextField_login = new javax.swing.JTextField();
        PassWordLabel = new javax.swing.JLabel();
        PasswordTextField_login = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        LogInButton = new javax.swing.JButton();
        loginNotes = new javax.swing.JLabel();
        PassWordLabel2 = new javax.swing.JLabel();
        About = new javax.swing.JPanel();
        SignIn = new javax.swing.JPanel();
        loginRootlabel1 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        NameTextField_signin = new javax.swing.JTextField();
        RollNoLabel1 = new javax.swing.JLabel();
        RollNoTextField_signin = new javax.swing.JTextField();
        PassWordLabel1 = new javax.swing.JLabel();
        PasswordTextField_signin = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        SignInButton = new javax.swing.JButton();
        FaceIdSignIn = new javax.swing.JLabel();
        AddFaceIDSignIN = new javax.swing.JButton();
        NoteSignIN = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        EmailTextField_signin = new javax.swing.JTextField();
        Admin = new javax.swing.JPanel();
        loginRootlabel2 = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        NameTextField_login1 = new javax.swing.JTextField();
        PassWordLabel3 = new javax.swing.JLabel();
        PasswordTextField_login1 = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        AdminLogin = new javax.swing.JButton();
        loginNotes1 = new javax.swing.JLabel();
        PassWordLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RootPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(36, 47, 65));
        menuPanel.setPreferredSize(new java.awt.Dimension(250, 601));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        AdminButton.setBackground(new java.awt.Color(36, 47, 65));
        AdminButton.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        AdminButton.setForeground(new java.awt.Color(255, 255, 255));
        AdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_account_box_white_24dp.png"))); // NOI18N
        AdminButton.setText("Admin");
        AdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminButtonMouseClicked(evt);
            }
        });
        AdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonActionPerformed(evt);
            }
        });

        LogINButton.setBackground(new java.awt.Color(36, 47, 65));
        LogINButton.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        LogINButton.setForeground(new java.awt.Color(255, 255, 255));
        LogINButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_person_white_24dp.png"))); // NOI18N
        LogINButton.setText("LogIN");
        LogINButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogINButtonMouseClicked(evt);
            }
        });

        SignINButton.setBackground(new java.awt.Color(36, 47, 65));
        SignINButton.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        SignINButton.setForeground(new java.awt.Color(255, 255, 255));
        SignINButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_person_add_white_24dp.png"))); // NOI18N
        SignINButton.setText("SignIN");
        SignINButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignINButtonMouseClicked(evt);
            }
        });

        AboutButton.setBackground(new java.awt.Color(36, 47, 65));
        AboutButton.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        AboutButton.setForeground(new java.awt.Color(255, 255, 255));
        AboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_import_contacts_white_24dp.png"))); // NOI18N
        AboutButton.setText("About");
        AboutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutButtonMouseClicked(evt);
            }
        });
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        AttandanceButton1.setBackground(new java.awt.Color(36, 47, 65));
        AttandanceButton1.setFont(new java.awt.Font("Kristen ITC", 0, 13)); // NOI18N
        AttandanceButton1.setForeground(new java.awt.Color(255, 255, 255));
        AttandanceButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_account_box_white_24dp.png"))); // NOI18N
        AttandanceButton1.setText("Attandance");
        AttandanceButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttandanceButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LogINButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignINButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AboutButton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdminButton)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(AttandanceButton1)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdminButton)
                .addGap(100, 100, 100)
                .addComponent(LogINButton)
                .addGap(43, 43, 43)
                .addComponent(SignINButton)
                .addGap(39, 39, 39)
                .addComponent(AboutButton)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(AttandanceButton1)
                    .addContainerGap(440, Short.MAX_VALUE)))
        );

        RootPanel.add(menuPanel, java.awt.BorderLayout.LINE_START);

        DetailsPanel.setBackground(new java.awt.Color(97, 212, 195));
        DetailsPanel.setLayout(new java.awt.CardLayout());

        Attandance.setBackground(new java.awt.Color(97, 212, 195));

        AddandancekeeperRootLabel.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        AddandancekeeperRootLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddandancekeeperRootLabel.setText("Attandance Keeper");

        FaceIdRootLabel.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        FaceIdRootLabel.setText("FaceID");

        FaceID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FaceID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_person_outline_white_48dp.png"))); // NOI18N

        Note.setText("NOTE: Enter your FaceId");

        AddFaceID.setBackground(new java.awt.Color(36, 47, 65));
        AddFaceID.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        AddFaceID.setForeground(new java.awt.Color(255, 255, 255));
        AddFaceID.setText("Start");
        AddFaceID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddFaceIDMouseClicked(evt);
            }
        });

        stop.setBackground(new java.awt.Color(36, 47, 65));
        stop.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        stop.setForeground(new java.awt.Color(255, 255, 255));
        stop.setText("stop");
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student", "Confirm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StudentTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                StudentTablePropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(StudentTable);

        confirm.setBackground(new java.awt.Color(36, 47, 65));
        confirm.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        confirm.setForeground(new java.awt.Color(255, 255, 255));
        confirm.setText("Confirm");
        confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmMouseClicked(evt);
            }
        });
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AttandanceLayout = new javax.swing.GroupLayout(Attandance);
        Attandance.setLayout(AttandanceLayout);
        AttandanceLayout.setHorizontalGroup(
            AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttandanceLayout.createSequentialGroup()
                .addContainerGap(361, Short.MAX_VALUE)
                .addComponent(AddandancekeeperRootLabel)
                .addGap(279, 279, 279))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttandanceLayout.createSequentialGroup()
                .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttandanceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Note)
                        .addGap(108, 108, 108))
                    .addGroup(AttandanceLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(AttandanceLayout.createSequentialGroup()
                                .addComponent(AddFaceID)
                                .addGap(53, 53, 53)
                                .addComponent(stop)
                                .addGap(393, 393, 393))
                            .addComponent(FaceID, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AttandanceLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttandanceLayout.createSequentialGroup()
                        .addComponent(confirm)
                        .addGap(37, 37, 37))))
            .addGroup(AttandanceLayout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(FaceIdRootLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AttandanceLayout.setVerticalGroup(
            AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttandanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddandancekeeperRootLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FaceIdRootLabel)
                .addGap(13, 13, 13)
                .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AttandanceLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AttandanceLayout.createSequentialGroup()
                        .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AttandanceLayout.createSequentialGroup()
                                .addComponent(FaceID, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AttandanceLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(AttandanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddFaceID)
                                    .addComponent(stop)
                                    .addComponent(confirm))
                                .addGap(37, 37, 37)))
                        .addComponent(Note)
                        .addGap(22, 22, 22))))
        );

        DetailsPanel.add(Attandance, "card3");

        LogIn.setBackground(new java.awt.Color(97, 212, 195));

        loginRootlabel.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        loginRootlabel.setForeground(new java.awt.Color(255, 255, 255));
        loginRootlabel.setText("LogIN");

        nameLabel.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");

        NameTextField_login.setBackground(new java.awt.Color(97, 212, 195));
        NameTextField_login.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NameTextField_login.setBorder(null);

        RollNoLabel.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        RollNoLabel.setForeground(new java.awt.Color(255, 255, 255));
        RollNoLabel.setText("Roll NO.");

        RollNoTextField_login.setBackground(new java.awt.Color(97, 212, 195));
        RollNoTextField_login.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        RollNoTextField_login.setBorder(null);
        RollNoTextField_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNoTextField_loginActionPerformed(evt);
            }
        });

        PassWordLabel.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        PassWordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassWordLabel.setText("PassWord");

        PasswordTextField_login.setBackground(new java.awt.Color(97, 212, 195));
        PasswordTextField_login.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PasswordTextField_login.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        LogInButton.setBackground(new java.awt.Color(36, 47, 65));
        LogInButton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        LogInButton.setForeground(new java.awt.Color(255, 255, 255));
        LogInButton.setText("LogIN");
        LogInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInButtonMouseClicked(evt);
            }
        });

        loginNotes.setText("Note: Enter your account details to login");

        PassWordLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        PassWordLabel2.setText("forgot password");
        PassWordLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassWordLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogInLayout = new javax.swing.GroupLayout(LogIn);
        LogIn.setLayout(LogInLayout);
        LogInLayout.setHorizontalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LogInLayout.createSequentialGroup()
                                .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(PassWordLabel2))
                            .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1)
                                .addComponent(PassWordLabel)
                                .addComponent(nameLabel)
                                .addComponent(NameTextField_login)
                                .addComponent(RollNoTextField_login)
                                .addComponent(PasswordTextField_login)
                                .addComponent(RollNoLabel)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(loginRootlabel))
                    .addGroup(LogInLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(loginNotes)))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        LogInLayout.setVerticalGroup(
            LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginRootlabel)
                .addGap(68, 68, 68)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(NameTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(RollNoLabel)
                .addGap(18, 18, 18)
                .addComponent(RollNoTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PassWordLabel)
                .addGap(18, 18, 18)
                .addComponent(PasswordTextField_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassWordLabel2))
                .addGap(41, 41, 41)
                .addComponent(loginNotes)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        DetailsPanel.add(LogIn, "card4");

        About.setBackground(new java.awt.Color(97, 212, 195));

        javax.swing.GroupLayout AboutLayout = new javax.swing.GroupLayout(About);
        About.setLayout(AboutLayout);
        AboutLayout.setHorizontalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        AboutLayout.setVerticalGroup(
            AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        DetailsPanel.add(About, "card5");

        SignIn.setBackground(new java.awt.Color(97, 212, 195));

        loginRootlabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        loginRootlabel1.setForeground(new java.awt.Color(255, 255, 255));
        loginRootlabel1.setText("SignIN");

        nameLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel1.setText("Name");

        NameTextField_signin.setBackground(new java.awt.Color(97, 212, 195));
        NameTextField_signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NameTextField_signin.setBorder(null);

        RollNoLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        RollNoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        RollNoLabel1.setText("Roll NO.");

        RollNoTextField_signin.setBackground(new java.awt.Color(97, 212, 195));
        RollNoTextField_signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        RollNoTextField_signin.setBorder(null);
        RollNoTextField_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollNoTextField_signinActionPerformed(evt);
            }
        });

        PassWordLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        PassWordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PassWordLabel1.setText("PassWord");

        PasswordTextField_signin.setBackground(new java.awt.Color(97, 212, 195));
        PasswordTextField_signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PasswordTextField_signin.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        SignInButton.setBackground(new java.awt.Color(36, 47, 65));
        SignInButton.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        SignInButton.setForeground(new java.awt.Color(255, 255, 255));
        SignInButton.setText("SignIN");
        SignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButtonMouseClicked(evt);
            }
        });
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });

        FaceIdSignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniproject/gui/ic_person_outline_white_48dp.png"))); // NOI18N

        AddFaceIDSignIN.setBackground(new java.awt.Color(36, 47, 65));
        AddFaceIDSignIN.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        AddFaceIDSignIN.setForeground(new java.awt.Color(255, 255, 255));
        AddFaceIDSignIN.setText("Add");
        AddFaceIDSignIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddFaceIDSignINMouseClicked(evt);
            }
        });

        NoteSignIN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NoteSignIN.setText("Note: Before entering faceID enter name and rollno first");

        nameLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel2.setText("Email Add.");

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        EmailTextField_signin.setBackground(new java.awt.Color(97, 212, 195));
        EmailTextField_signin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EmailTextField_signin.setBorder(null);

        javax.swing.GroupLayout SignInLayout = new javax.swing.GroupLayout(SignIn);
        SignIn.setLayout(SignInLayout);
        SignInLayout.setHorizontalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayout.createSequentialGroup()
                .addGap(439, 439, 439)
                .addComponent(loginRootlabel1)
                .addGap(218, 456, Short.MAX_VALUE))
            .addGroup(SignInLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addComponent(PassWordLabel1)
                            .addComponent(nameLabel1)
                            .addComponent(NameTextField_signin)
                            .addComponent(PasswordTextField_signin)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(RollNoLabel1)
                            .addComponent(RollNoTextField_signin, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignInLayout.createSequentialGroup()
                                .addComponent(FaceIdSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddFaceIDSignIN)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SignInLayout.createSequentialGroup()
                                .addComponent(NoteSignIN)
                                .addGap(104, 104, 104))))
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailTextField_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        SignInLayout.setVerticalGroup(
            SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginRootlabel1)
                .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FaceIdSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SignInLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(AddFaceIDSignIN)))
                        .addGap(75, 75, 75)
                        .addComponent(NoteSignIN))
                    .addGroup(SignInLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(nameLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(NameTextField_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(RollNoLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(RollNoTextField_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(PassWordLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(PasswordTextField_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(nameLabel2)
                .addGap(26, 26, 26)
                .addComponent(EmailTextField_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(SignInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        DetailsPanel.add(SignIn, "card4");

        Admin.setBackground(new java.awt.Color(97, 212, 195));

        loginRootlabel2.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        loginRootlabel2.setForeground(new java.awt.Color(255, 255, 255));
        loginRootlabel2.setText("Admin LogIN");

        nameLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel3.setText("User Name");

        NameTextField_login1.setBackground(new java.awt.Color(97, 212, 195));
        NameTextField_login1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NameTextField_login1.setBorder(null);

        PassWordLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        PassWordLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PassWordLabel3.setText("PassWord");

        PasswordTextField_login1.setBackground(new java.awt.Color(97, 212, 195));
        PasswordTextField_login1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PasswordTextField_login1.setBorder(null);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));

        AdminLogin.setBackground(new java.awt.Color(36, 47, 65));
        AdminLogin.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        AdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        AdminLogin.setText("LogIN");
        AdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginMouseClicked(evt);
            }
        });
        AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginActionPerformed(evt);
            }
        });

        loginNotes1.setText("Note: Enter your account details to login");

        PassWordLabel4.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        PassWordLabel4.setText("forgot password");
        PassWordLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassWordLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminLayout.createSequentialGroup()
                                .addComponent(AdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(PassWordLabel4))
                            .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator8)
                                .addComponent(PassWordLabel3)
                                .addComponent(nameLabel3)
                                .addComponent(NameTextField_login1)
                                .addComponent(PasswordTextField_login1)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(loginRootlabel2))
                    .addGroup(AdminLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(loginNotes1)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginRootlabel2)
                .addGap(68, 68, 68)
                .addComponent(nameLabel3)
                .addGap(18, 18, 18)
                .addComponent(NameTextField_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(PassWordLabel3)
                .addGap(18, 18, 18)
                .addComponent(PasswordTextField_login1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassWordLabel4))
                .addGap(41, 41, 41)
                .addComponent(loginNotes1)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        DetailsPanel.add(Admin, "card6");

        RootPanel.add(DetailsPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollNoTextField_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNoTextField_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNoTextField_loginActionPerformed

    private void RollNoTextField_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollNoTextField_signinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollNoTextField_signinActionPerformed

    private void AdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminButtonMouseClicked
        DetailsPanel.removeAll();
        DetailsPanel.add(Admin);
        DetailsPanel.repaint();
        DetailsPanel.revalidate();
    }//GEN-LAST:event_AdminButtonMouseClicked

    private void LogINButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogINButtonMouseClicked
        DetailsPanel.removeAll();
        DetailsPanel.add(LogIn);
        DetailsPanel.repaint();
        DetailsPanel.revalidate();
    }//GEN-LAST:event_LogINButtonMouseClicked

    private void SignINButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignINButtonMouseClicked
        DetailsPanel.removeAll();
        DetailsPanel.add(SignIn);
        DetailsPanel.repaint();
        DetailsPanel.revalidate();
    }//GEN-LAST:event_SignINButtonMouseClicked

    private void AboutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutButtonMouseClicked
        DetailsPanel.removeAll();
        DetailsPanel.add(About);
        DetailsPanel.repaint();
        DetailsPanel.revalidate();
    }//GEN-LAST:event_AboutButtonMouseClicked

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void AddFaceIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFaceIDMouseClicked
        if(capture==null)
        {
            DefaultTableModel model=(DefaultTableModel) StudentTable.getModel();
            capture=new FaceCapture(FaceID,model);
            capture.start();
        }
        else if(capture.t!=null && !capture.t.isAlive())
        {
            capture.start();
        }
    }//GEN-LAST:event_AddFaceIDMouseClicked

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignInButtonActionPerformed

    private void AddFaceIDSignINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFaceIDSignINMouseClicked
        if(csFrame)
        {
            return;
        }
        String rollno=RollNoTextField_signin.getText();
        if(rollno==null || rollno.equals(""))
        {
            System.out.println("Enter rollno first");
            return;
        }
        
        CSFrame.start(rollno,FaceIdSignIn,1);
        csFrame=true;        
    }//GEN-LAST:event_AddFaceIDSignINMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        if(capture!=null)
        {
            capture.stop();
        }
    }//GEN-LAST:event_stopMouseClicked

    private void confirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmMouseClicked
        if(cinfirm_window)
        {
            return;
        }
        int index=-1;
        try{
            index=StudentTable.getSelectedRow();
        }
        catch(Exception e)
        {
            /// Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, e);
        }
        
        if(index==-1)
        {
            System.out.println("Select row in the tabe first to confirm it");
        }
        else
        {
            DefaultTableModel model=(DefaultTableModel) StudentTable.getModel();
            Confirm fingureprint=new Confirm(index,model);
            fingureprint.setVisible(true);
            cinfirm_window=true;
        }
    }//GEN-LAST:event_confirmMouseClicked

    private void LogInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInButtonMouseClicked
        // Check inputed data and is legimate user enter into his account
        String Name=NameTextField_login.getText();
        int Rollno;
        
        if(RollNoTextField_login.getText().isEmpty())
        {
            loginNotes.setText("Note: rollno field empty");
            return;
        }
        
        try
        {
            Rollno=Integer.parseInt(RollNoTextField_login.getText());
        }
        catch(Exception e)
        {
            loginNotes.setText("Note: problem in rollno");
            /// Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, e);
            return;
        }
        String Password=PasswordTextField_login.getText();
        
        if(Name.isEmpty() || Password.isEmpty() || Name.equals("") || Password.equals(""))
        {
            loginNotes.setText("Note: Enter valid data");
            return;
        }
        
        
        String Email=null;
        boolean result=false;
        Student_database db=new Student_database();
        try {
            Email=db.getemail(Rollno);
            result=db.check_user_input(Name,Password,Rollno);
        } catch (Exception ex) {
            /// Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            loginNotes.setText("Note: problem with database try again");
            return;
        }
        
        try {
            db.stmt.close();
            db.c.commit();
            db.c.close();
        } catch (SQLException ex) {
            /// Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            loginNotes.setText("Note: Some problem ooccured with database try again");
            return;
        }
        
        if(result)
        {
            AccountDetails details=new AccountDetails(Rollno);
            details.setVisible(true);
            dispose();
            new SendEmail(SendEmail.LOG_IN,Name,Email);
        }
        else
        {
            loginNotes.setText("Note: Wrong user details");
        }
    }//GEN-LAST:event_LogInButtonMouseClicked

    private void SignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseClicked
        /// sign in
        boolean problem=false;
        
        ///check if image is added or not
        
        ///
        String Name=NameTextField_signin.getText();
        
        if(RollNoTextField_signin.getText().isEmpty())
        {
            NoteSignIN.setText("Note: Enter roll no");
            return;
        }
        
        int Rollno;
        try
        {
            Rollno=Integer.parseInt(RollNoTextField_signin.getText());
        }
        catch(Exception e)
        {
            NoteSignIN.setText("Note: Invalid roll no");
            return;
        }
        ///check for unique rollno
        
        String Password=PasswordTextField_signin.getText();
        String Email=EmailTextField_signin.getText();
        
        if(Name.isEmpty() || Password.isEmpty() || Email.isEmpty())
        {
            NoteSignIN.setText("Note: Invalid data input");
            return;
        }
        
        
        boolean result=false,unique_roll=false;
        Student_database db=new Student_database();
        
        try {
            unique_roll=db.check_roll(Rollno);
        } 
        catch (SQLException ex) 
        {
            NoteSignIN.setText("Note: Enter proper rollno.");
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }
        
        if(!unique_roll)
        {
            NoteSignIN.setText("Note: Enter unique rollno.");
            return;
        }
        
        try {
            System.out.println(Password+" "+Rollno+" "+Name+" "+Email);
            result=db.singup(Password,Rollno,Name,Email);
        } catch (Exception ex) {
            // Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            problem=true;
        }
        
        
        if(!result)
        {
           NoteSignIN.setText("Note: Some problem occured while creating your account please check your input");
           return;
        }
        
        try {
            db.stmt.close();
            db.c.commit();
            db.c.close();
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            problem=true;
        }
        
        
        
        if(problem)
        {
            NoteSignIN.setText("Some problem occured please try again");
        }
        else
        {
            new SendEmail(SendEmail.SIGN_IN,Name,Email);
            NoteSignIN.setText("Your account has been created please login into your account");
        }
    }//GEN-LAST:event_SignInButtonMouseClicked

    private void PassWordLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassWordLabel2MouseClicked
        forgot_password frame=new forgot_password();
        frame.setVisible(true);
    }//GEN-LAST:event_PassWordLabel2MouseClicked

    private void AttandanceButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttandanceButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttandanceButton1MouseClicked

    private void AdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonActionPerformed
        DetailsPanel.removeAll();
        DetailsPanel.add(LogIn);
        DetailsPanel.repaint();
        DetailsPanel.revalidate();       
//  admin frame = new admin();
        // frame.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_AdminButtonActionPerformed

    private void AdminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginMouseClicked
        
       
       
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginMouseClicked

    private void PassWordLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassWordLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordLabel4MouseClicked

    private void AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginActionPerformed
       String Name=NameTextField_login1.getText();
       
        
      
        
     
        String Password=PasswordTextField_login1.getText();
         System.out.println(Name);
       System.out.println(Password);
       if(Name.isEmpty() || Password.isEmpty() || Name.equals("") || Password.equals(""))
        {
            loginNotes.setText("Note: Enter valid data");
            return;
        }
      
        else if(Name.equals("Darshan")&Password.equals("LOGIN"))
        {
            admin myadmin= new admin();
            myadmin.setVisible(true);
        }
     //    TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmActionPerformed

    private void StudentTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_StudentTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentTablePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton AddFaceID;
    private javax.swing.JButton AddFaceIDSignIN;
    private javax.swing.JLabel AddandancekeeperRootLabel;
    private javax.swing.JPanel Admin;
    private javax.swing.JButton AdminButton;
    private javax.swing.JButton AdminLogin;
    private javax.swing.JPanel Attandance;
    private javax.swing.JButton AttandanceButton1;
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JTextField EmailTextField_signin;
    private javax.swing.JLabel FaceID;
    private javax.swing.JLabel FaceIdRootLabel;
    private javax.swing.JLabel FaceIdSignIn;
    private javax.swing.JButton LogINButton;
    private javax.swing.JPanel LogIn;
    private javax.swing.JButton LogInButton;
    private javax.swing.JTextField NameTextField_login;
    private javax.swing.JTextField NameTextField_login1;
    private javax.swing.JTextField NameTextField_signin;
    private javax.swing.JLabel Note;
    private javax.swing.JLabel NoteSignIN;
    private javax.swing.JLabel PassWordLabel;
    private javax.swing.JLabel PassWordLabel1;
    private javax.swing.JLabel PassWordLabel2;
    private javax.swing.JLabel PassWordLabel3;
    private javax.swing.JLabel PassWordLabel4;
    private javax.swing.JPasswordField PasswordTextField_login;
    private javax.swing.JPasswordField PasswordTextField_login1;
    private javax.swing.JPasswordField PasswordTextField_signin;
    private javax.swing.JLabel RollNoLabel;
    private javax.swing.JLabel RollNoLabel1;
    private javax.swing.JTextField RollNoTextField_login;
    private javax.swing.JTextField RollNoTextField_signin;
    private javax.swing.JPanel RootPanel;
    private javax.swing.JButton SignINButton;
    private javax.swing.JPanel SignIn;
    private javax.swing.JButton SignInButton;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel loginNotes;
    private javax.swing.JLabel loginNotes1;
    private javax.swing.JLabel loginRootlabel;
    private javax.swing.JLabel loginRootlabel1;
    private javax.swing.JLabel loginRootlabel2;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
